# for tests
required = ["golang.org/x/lint"]

[[override]]
  name = "golang.org/x/tools"
  revision = "a019f6b7c5bfcffdf421924fc0ddb74b867a53f2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.2.0"

[prune]
  go-tests = true
  unused-packages = true
